#! /bin/sh
#===============================
#
# amixer
#
# 2020/10/06 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
amixer set "DVC In"  20%

amixer -D hw:1 set "pcm3168a DAC1" 50%
amixer -D hw:1 set "pcm3168a DAC2" 50%
amixer -D hw:1 set "pcm3168a DAC3" 50%
amixer -D hw:1 set "pcm3168a DAC4" 50%
