#! /bin/sh
#===============================
#
# amixer
#
# 2020/10/06 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
amixer set "DVC Out" 1%
amixer set "DVC In"  20%
