#! /bin/sh
TOP=`readlink -f "$0" | xargs dirname | xargs dirname | xargs dirname`

echo "+-ulcb--+"
echo "|(i) ( )|"
echo "+-------+"
echo "+-kf----+"
echo "|( ) ( )|"
echo "|( ) (o)|"
echo "+-------+"

test() {
	DIR=$1
	LIST="19 28 37 46"

	echo "${DIR} split test"
	for list in ${LIST}
	do
		${TOP}/script/sample-test-loopback.sh -o plughw:0,4 -f ${TOP}/renesas/${DIR}/${list}.wav -e ${list}
	done
}

test 44100
test 48000
